apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app.kubernetes.io/instance: sample-app
  name: sample-app
spec:
  host: sample-app-default.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: sample-app
    weight: 100
  wildcardPolicy: None
